---
version: "2.0"
services:
  node:
    image: ghcr.io/akash-network/cosmos-omnibus:v0.3.30-kava-v0.23.0
    env:
      - MONIKER=my-moniker-1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/kava/chain.json
      # If you don't want to use state-sync or it does not work, then you can use the snapshots:
      # Obtain the current snapshot URL via this Polkachu site for Kava nodes:
      # https://polkachu.com/tendermint_snapshots/kava
      # Populated example SNAPSHOT_URL provided below
      # - SNAPSHOT_URL=https://snapshots.polkachu.com/snapshots/kava/kava_3967613.tar.lz4
      # - SNAPSHOT_DATA_PATH=data
      # - ADDRBOOK_URL=https://snapshots.polkachu.com/addrbook/kava/addrbook.json
      # Statesync for the Kava chain currerntly fails.  In the future - to test statesync anew - uncomment the P2P and STATESYNC lines below.
      - P2P_POLKACHU=1
      - STATESYNC_POLKACHU=1
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true
#################################
# Required for persistent storage
    params:
      storage:
        data:
          mount: /root/.kava
#################################
profiles:
  compute:
    node:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
#################################
# Persistent storage enabled by default with SSD.
#################################
        storage:
          - size: 1Gi
          - name: data
            size: 400Gi
            attributes:
              persistent: true
              class: beta2
              # Choose Storage Type : beta1 (HDD), beta2 (SSD), beta3 (NVMe)
#################################
# To use ephemeral storage, comment out persistent storage blocks and uncomment below
#################################
#        storage:
#          size: 100Gi
#################################
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        node:
          denom: uakt
          amount: 10000
deployment:
  node:
    akash:
      profile: node
      count: 1
