---
version: "2.0"
services:
  node:
    image: ghcr.io/akash-network/cosmos-omnibus:v0.3.30-nois-v1.0.2
    env:
      - MONIKER=node_1
      # - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/nois/chain.json
      - CHAIN_ID=nois-1
      - GENESIS_URL=https://raw.githubusercontent.com/noislabs/networks/nois1.final.1/nois-1/genesis.json
      - P2P_SEEDS=b3e3bd436ee34c39055a4c9946a02feec232988c@seeds.cros-nest.com:56656,babc3f3f7804933265ec9c40ad94f4da8e9e0017@seed.rhinostake.com:17356,ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:17356,72cd4222818d25da5206092c3efc2c0dd0ec34fe@161.97.96.91:36656,20e1000e88125698264454a884812746c2eb4807@seeds.lavenderfive.com:17356,c8db99691545545402a1c45fa897f3cb1a05aea6@nois-mainnet-seed.itrocket.net:36656
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true
#################################
# Required for persistent storage
    params:
      storage:
        data:
          mount: /root/.noisd
#################################
profiles:
  compute:
    node:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
#################################
# Persistent storage enabled by default with SSD.
#################################
        storage:
          - size: 1Gi
          - name: data
            size: 400Gi
            attributes:
              persistent: true
              class: beta2
              # Choose Storage Type : beta1 (HDD), beta2 (SSD), beta3 (NVMe)
#################################
# To use ephemeral storage, comment out persistent storage blocks and uncomment below
#################################
#        storage:
#          size: 100Gi
#################################
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        node:
          denom: uakt
          amount: 10000
deployment:
  node:
    akash:
      profile: node
      count: 1
