---
version: "2.0"
services:
  node:
    image: ghcr.io/akash-network/cosmos-omnibus:v0.3.30-jackal-v2.0.0
    env:
      - MONIKER=my-moniker-1
      - CHAIN_ID=jackal-1
      - GENESIS_URL=https://cdn.discordapp.com/attachments/1002389406650466405/1034968352591986859/updated_genesis2.json
      - P2P_SEEDS=ec38fb158ffb0272c4b7c951fc790a8f9849e280@198.244.212.27:26656,ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:17556
      - MINIMUM_GAS_PRICES=0.002ujkl
      - P2P_POLKACHU=1
      - STATESYNC_POLKACHU=1
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true
#################################
# Required for persistent storage
    params:
      storage:
        data:
          mount: /root/.canine
#################################
profiles:
  compute:
    node:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
#################################
# Persistent storage enabled by default with SSD.
#################################
        storage:
          - size: 1Gi
          - name: data
            size: 400Gi
            attributes:
              persistent: true
              class: beta2
              # Choose Storage Type : beta1 (HDD), beta2 (SSD), beta3 (NVMe)
#################################
# To use ephemeral storage, comment out persistent storage blocks and uncomment below
#################################
#        storage:
#          size: 100Gi
#################################
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        node:
          denom: uakt
          amount: 10000
deployment:
  node:
    akash:
      profile: node
      count: 1
