---
version: "2.0"
services:
  node:
    image: ghcr.io/akash-network/cosmos-omnibus:v0.3.30-bitsong-v0.12.0
    env:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/bitsong/chain.json
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true
#################################
# Required for persistent storage
    params:
      storage:
        data:
          mount: /root/.bitsongd
#################################
profiles:
  compute:
    node:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
#################################
# Persistent storage enabled by default with SSD.
#################################
        storage:
          - size: 1Gi
          - name: data
            size: 400Gi
            attributes:
              persistent: true
              class: beta2
              # Choose Storage Type : beta1 (HDD), beta2 (SSD), beta3 (NVMe)
#################################
# To use ephemeral storage, comment out persistent storage blocks and uncomment below
#################################
#        storage:
#          size: 100Gi
#################################
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        node:
          denom: uakt
          amount: 10000
deployment:
  node:
    akash:
      profile: node
      count: 1
