name: publish
on:
  push:
    tags:
      - v*


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # hacks
          - project: kava
            env:     KAVA
            version: v0.14.1
            bin:     kvd
          - project: gaiad
            env:     GAIAD
            version: v4.2.1
            bin:     gaiad
          - project: dvpn
            env:     DVPN
            version: v0.5.0
            bin:     sentinelhub
          - project: akash
            env:     AKASH
            version: v0.12.1
            bin:     akash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: build
        run: |
          ${{matrix.env}}_VERSION="${{matrix.version}}" make build-${{matrix.project}}
      - name: publish
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin
          docker build . --tag ghcr.io/ovrclk/cosmos-omnibus:${GITHUB_REF#refs/tags/}-${{matrix.project}}-${{matrix.version}} \
            --build-arg PROJECT=${{matrix.project}}         \
            --build-arg PROJECT_VERSION=${{matrix.version}} \
            --build-arg PROJECT_BIN=${{matrix.bin}}
          docker push ghcr.io/ovrclk/cosmos-omnibus:${GITHUB_REF#refs/tags/}-${{matrix.project}}-${{matrix.version}}
